name: Build and Test ROS Code

on:
  push:
    # branches:
    #   - main
  pull_request:
    # branches:
    #   - main

jobs:
  humble_build:
    runs-on: ubuntu-22.04
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get install qtbase5-dev qt5-qmake qtbase5-dev-tools qtbase5-private-dev qt5* libeigen3-dev libgtest-dev -y
      - name: Build
        run: |
          /bin/bash -c \
          "source /opt/ros/humble/setup.bash \
          && sudo apt-get install qtbase5-dev qt5-qmake qtbase5-dev-tools qtbase5-private-dev qt5* libeigen3-dev libgtest-dev -y  \
          && rm -rf build \
          && mkdir build/ \
          && cd build/ \
          && cmake .. \
          && make -j$(nproc)"
