name: Build and Test ROS Code

on:
  push:
    # branches:
    #   - main
  pull_request:
    # branches:
    #   - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."


    - name: Pull ROS Docker image
      run: docker pull ros:melodic

    - name: Build ROS code
      run: |
        docker run \
          -v $(pwd):/workspace \
          -w /workspace \
          ros:melodic \
          ls

    - name: Run ROS code
      run: |
        docker run --rm -it \
          -v $(pwd):/workspace \
          -w /workspace \
          ros:melodic \
          roslaunch my_ros_package my_ros_launch_file.launch