name: ROS1:Noetic(20.04)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  noetic_build:
    runs-on: ubuntu-20.04
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: noetic
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get install qtbase5-dev qt5-qmake qtbase5-dev-tools qtbase5-private-dev qt5* libeigen3-dev libgtest-dev -y
      - name: Build
        run: |
          /bin/bash -c \
          "source /opt/ros/noetic/setup.bash \
          && sudo apt-get install qtbase5-dev qt5-qmake qtbase5-dev-tools qtbase5-private-dev qt5* libeigen3-dev libgtest-dev -y  \
          && rm -rf build \
          && mkdir build/ \
          && cd build/ \
          && cmake .. -DBUILD_WITH_TEST=ON\
          && make -j$(nproc) \
          && make install
          "
      - name: Test
        run: |
          /bin/bash -c \
          "source /opt/ros/noetic/setup.bash \
          && cd build \
          && make test"