name: ROS1:Melodic(18.04)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  melodic_build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
    steps:
      - uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: melodic
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get install qtbase5-dev qt5-qmake qtbase5-dev-tools qtbase5-private-dev qt5* libeigen3-dev libgtest-dev -y
      - name: update gtest
        run: |
          wget https://github.com/google/googletest/archive/refs/tags/release-1.12.1.tar.gz \
          && tar -zxvf release-1.12.1.tar.gz \
          && cd googletest-release-1.12.1 \
          && mkdir build \
          && cd build \
          && cmake .. \
          && make -j$(nproc) \
          && sudo make install
      - name: Build
        run: |
          /bin/bash -c \
          "source /opt/ros/melodic/setup.bash \
          && sudo apt-get install qtbase5-dev qt5-qmake qtbase5-dev-tools qtbase5-private-dev qt5* libeigen3-dev libgtest-dev -y  \
          && rm -rf build \
          && mkdir build/ \
          && cd build/ \
          && cmake .. -DBUILD_WITH_TEST=ON\
          && make -j$(nproc) \
          && make install
          "
      - name: Test
        run: |
          /bin/bash -c \
          "source /opt/ros/foxy/setup.bash \
          && cd build \
          && make test"